on:
  schedule:
    # 5 am UTC is 10 pm PDT (summer) or 9 pm PST (winter)
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      dont_ping:
        description: 'dont ping'
        required: false
        type: boolean

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: figure out who didnt commit yet
        run: |
          echo "do not ping?: $DONT_PING"
          # https://stackoverflow.com/a/9849524
          SINCE=$(TZ=America/Los_Angeles node random-javaProject-LmaoHaha/beginning-of-the-day.js)
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/NolanChai/Commit-Challenge-2024/commits?since=$SINCE" > commits.json
          node random-javaProject-LmaoHaha/read-commits.js || gh issue comment 1 --body "$(cat issuemsg.txt)"
        env:
          # https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DONT_PING: ${{ inputs.dont_ping }}
    permissions:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
      issues: write
