on:
  schedule:
    # 5 am UTC is 10 pm PDT (summer) or 9 pm PST (winter)
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      hello:
        description: 'hello lol'
        required: false
        type: boolean

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for Discord webhook URL
        run: |
          echo "discord webhook url is"
          echo $REMINDER_WEBHOOK
          echo "hello: $HELLO"
          pwd
          ls -al
          gh issue comment 1 --body "hi @SheepTester. it's $(date)" && true
        env:
          REMINDER_WEBHOOK: ${{ secrets.REMINDER_WEBHOOK }}
          # https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HELLO: ${{ inputs.hello }}
